### PR TITLE
Add support for TypeParameters and SingleVariableDesignations for C#

### PR DESCRIPTION
**Pull request by sagi1623**

### CODE REVIEW

**Comment by sagi1623** [comment]
Hello @olafurpg,

I would like to ask you if you are fine with me tagging you on PRs when they are reviewable?
Or what is the process? Should I just leave it and you or someone else will pick it up at some point?
I know you have other stuff to work on and I don't want to be pushy.

**Comment by olafurpg** [comment]
@sagi1623 Tagging me is great! It's easy for me to miss the notification otherwise.

**Review by olafurpg — APPROVED** [review]
This is a great fix! Thank you @sagi1623

**Comment by olafurpg** [comment]
https://github.com/sourcegraph/scip-dotnet/releases/tag/v0.2.2

**Pull request merged**
