### PR TITLE
Add support for Foreach statement in C# 

### PR DESCRIPTION
**Pull request by sagi1623**

### CODE REVIEW

**Comment by sagi1623** [comment]
Hello @olafurpg,
I would be happy to get a review for this PR when you have some time.

**Review by olafurpg — APPROVED** [review]
LGTM 👍🏻 There is a conflict blocking merge.

**Comment by sagi1623** [comment]
Conflict resolved.
Thanks a lot for your reviews!

**Comment by olafurpg** [comment]
Thank you! https://github.com/sourcegraph/scip-dotnet/releases/tag/v0.2.3

**Pull request merged**
